### ISSUE TITLE
Add extra arguments to white list pull

### ISSUE THREAD

**Issue by Jelloeater** [db0/pythonseer#7]
Would be nice if you could have extra arguments right in the function

Ex

```python
    d = requests.get(url='https://fediseer.com/api/v1/whitelist',
                 params={'endorsements': 3, 'guarantors': 4, 'software_csv': 'lemmy', 'limit': 100, 'domains': True}).json()['domains']
```

Change would be here

https://github.com/Fediseer/pythonseer/blob/main/pythonseer/whitelist.py#L29

**Comment by db0** [comment]
Yes I need to update this SDK

**Comment by Jelloeater** [comment]
@db0 I might do a PR, if I have time 😄

**Comment by Jelloeater** [comment]
https://github.com/Fediseer/pythonseer/pull/8 ❤️
